main: net.jandie1505.nomessagesigning.NoMessageSigning
name: NoMessageSigning
version: 1.0
api-version: 1.20
commands:
  nomessagesigning:
    description: Info command and reload subcommand which can only be used by console
    usage: /nomessagesigning [reload]
