main: net.jandie1505.nomessagesignatures.NoMessageSignatures
name: NoMessageSignatures
version: 1.3
api-version: 1.19
commands:
  nomessagesignatures:
    description: Info command, mode subcommand and reload subcommand which can only be used by console.
    usage: /nomessagesignatures [mode/reload]

