main: net.jandie1505.nomessagesignatures.NoMessageSignatures
name: NoMessageSignatures
version: 1.0
api-version: 1.20
commands:
  nomessagesignatures:
    description: Info command and reload subcommand which can only be used by console
    usage: /nomessagesignatures [reload]
